name: cloudrun-deploy
on:
  push:
    branches:
      - Flask-Sample-Test
jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: sample-app
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:
        - id: 'auth'
            uses: 'google-github-actions/auth@v0'
            with:
              credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        #- name: Test Docker image
        #  run: docker run $IMAGE_NAME sh -c "go test -v"

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region us-central1 --platform managed
